name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.7.0
  flutter_3d_controller: ^2.3.0
  flutter_ble_peripheral: ^2.0.1
  flutter_blue_plus: ^2.0.2
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.0.7
  uuid: ^4.5.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  model_viewer_plus: ^1.7.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/json/prefecher.json
    - lib/json/birthday.json
    - lib/json/birthday_trivia.json
